

<!DOCTYPE html>
<html lang="en">
<?php
$task = "transcribe";
include(dirname(__FILE__).'/../common/header.php');


?>


<div style="text-align: center;" class="col-md-10 col-md-offset-1">
    <h2>Results</h2>
    <h5 style="text-align: right;">*(min, mean, max) - counts</h5>
    <table class="table">

    <tr><td colspan = "2"></td><td colspan="2">baseline</td><td colspan="2">scim</td></tr>
    <tr><td></td><td></td><td>pretest</td><td>posttest</td><td>pretest</td><td>posttest</td></tr>
    <tr><td rowspan="3" style="vertical-align: middle;">Summary</td><td>S</td>
        <td>(<?php echo $this->simple_results['baseline']['summarytone'][1]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][1]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][1]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['summarytone'][1]['s1_3+s2_3+s3_3+s4_3']['counts']; ?> </td>
        <td>(<?php echo $this->simple_results['baseline']['summarytone'][0]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][0]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][0]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['summarytone'][0]['s1_3+s2_3+s3_3+s4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['summarytone'][1]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['scim']['summarytone'][1]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['summarytone'][1]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['summarytone'][1]['s1_3+s2_3+s3_3+s4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['summarytone'][0]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['scim']['summarytone'][0]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['summarytone'][0]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['summarytone'][0]['s1_3+s2_3+s3_3+s4_3']['counts']; ?></td>
    </tr>
    <tr><td>C</td>
        <td>(<?php echo $this->simple_results['baseline']['summarytone'][1]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][1]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][1]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['summarytone'][1]['c1_3+c2_3+c3_3+c4_3']['counts']; ?> </td>
        <td>(<?php echo $this->simple_results['baseline']['summarytone'][0]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][0]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][0]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['summarytone'][0]['c1_3+c2_3+c3_3+c4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['summarytone'][1]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['scim']['summarytone'][1]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['summarytone'][1]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['summarytone'][1]['c1_3+c2_3+c3_3+c4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['summarytone'][0]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['scim']['summarytone'][0]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['summarytone'][0]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['summarytone'][0]['c1_3+c2_3+c3_3+c4_3']['counts']; ?></td>
    </tr>
    <tr><td>I/M</td>
        <td>(<?php echo $this->simple_results['baseline']['summarytone'][1]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][1]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][1]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['summarytone'][1]['i1_3+i2_3+m1_3+m2_3']['counts']; ?> </td>
        <td>(<?php echo $this->simple_results['baseline']['summarytone'][0]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][0]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['summarytone'][0]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['summarytone'][0]['i1_3+i2_3+m1_3+m2_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['summarytone'][1]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['scim']['summarytone'][1]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['scim']['summarytone'][1]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['scim']['summarytone'][1]['i1_3+i2_3+m1_3+m2_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['summarytone'][0]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['scim']['summarytone'][0]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['scim']['summarytone'][0]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['scim']['summarytone'][0]['i1_3+i2_3+m1_3+m2_3']['counts']; ?></td>
    </tr>
    <tr><td rowspan="3" style="vertical-align: middle;">Tag</td><td>S</td>
        <td>(<?php echo $this->simple_results['baseline']['tag'][1]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['tag'][1]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['tag'][1]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['tag'][1]['s1_3+s2_3+s3_3+s4_3']['counts']; ?> </td>
        <td>(<?php echo $this->simple_results['baseline']['tag'][0]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['tag'][0]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['tag'][0]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['tag'][0]['s1_3+s2_3+s3_3+s4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['tag'][1]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['scim']['tag'][1]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['tag'][1]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['tag'][1]['s1_3+s2_3+s3_3+s4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['tag'][0]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['scim']['tag'][0]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['tag'][0]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['tag'][0]['s1_3+s2_3+s3_3+s4_3']['counts']; ?></td>
    </tr>
    <tr><td>C</td>
        <td>(<?php echo $this->simple_results['baseline']['tag'][1]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['tag'][1]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['tag'][1]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['tag'][1]['c1_3+c2_3+c3_3+c4_3']['counts']; ?> </td>
        <td>(<?php echo $this->simple_results['baseline']['tag'][0]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['tag'][0]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['tag'][0]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['tag'][0]['c1_3+c2_3+c3_3+c4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['tag'][1]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['scim']['tag'][1]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['tag'][1]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['tag'][1]['c1_3+c2_3+c3_3+c4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['tag'][0]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['scim']['tag'][0]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['tag'][0]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['tag'][0]['c1_3+c2_3+c3_3+c4_3']['counts']; ?></td>
    </tr>
    <tr><td>I/M</td>
        <td>(<?php echo $this->simple_results['baseline']['tag'][1]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['baseline']['tag'][1]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['tag'][1]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['tag'][1]['i1_3+i2_3+m1_3+m2_3']['counts']; ?> </td>
        <td>(<?php echo $this->simple_results['baseline']['tag'][0]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['baseline']['tag'][0]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['tag'][0]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['tag'][0]['i1_3+i2_3+m1_3+m2_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['tag'][1]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['scim']['tag'][1]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['scim']['tag'][1]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['scim']['tag'][1]['i1_3+i2_3+m1_3+m2_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['tag'][0]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['scim']['tag'][0]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['scim']['tag'][0]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['scim']['tag'][0]['i1_3+i2_3+m1_3+m2_3']['counts']; ?></td>
    </tr>
    <tr><td rowspan="3" style="vertical-align: middle;">Connect</td><td>S</td>
        <td>(<?php echo $this->simple_results['baseline']['connect'][1]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['connect'][1]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['connect'][1]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['connect'][1]['s1_3+s2_3+s3_3+s4_3']['counts']; ?> </td>
        <td>(<?php echo $this->simple_results['baseline']['connect'][0]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['connect'][0]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['connect'][0]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['connect'][0]['s1_3+s2_3+s3_3+s4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['connect'][1]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['scim']['connect'][1]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['connect'][1]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['connect'][1]['s1_3+s2_3+s3_3+s4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['connect'][0]['s1_3+s2_3+s3_3+s4_3']['min']; ?>, <?php echo $this->simple_results['scim']['connect'][0]['s1_3+s2_3+s3_3+s4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['connect'][0]['s1_3+s2_3+s3_3+s4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['connect'][0]['s1_3+s2_3+s3_3+s4_3']['counts']; ?></td>
    </tr>
    <tr><td>C</td>
        <td>(<?php echo $this->simple_results['baseline']['connect'][1]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['connect'][1]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['connect'][1]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['connect'][1]['c1_3+c2_3+c3_3+c4_3']['counts']; ?> </td>
        <td>(<?php echo $this->simple_results['baseline']['connect'][0]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['baseline']['connect'][0]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['connect'][0]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['connect'][0]['c1_3+c2_3+c3_3+c4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['connect'][1]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['scim']['connect'][1]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['connect'][1]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['connect'][1]['c1_3+c2_3+c3_3+c4_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['connect'][0]['c1_3+c2_3+c3_3+c4_3']['min']; ?>, <?php echo $this->simple_results['scim']['connect'][0]['c1_3+c2_3+c3_3+c4_3']['mean']; ?>, <?php echo $this->simple_results['scim']['connect'][0]['c1_3+c2_3+c3_3+c4_3']['max']; ?>) - <?php echo $this->simple_results['scim']['connect'][0]['c1_3+c2_3+c3_3+c4_3']['counts']; ?></td>
    </tr>
    <tr><td>I/M</td>
        <td>(<?php echo $this->simple_results['baseline']['connect'][1]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['baseline']['connect'][1]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['connect'][1]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['connect'][1]['i1_3+i2_3+m1_3+m2_3']['counts']; ?> </td>
        <td>(<?php echo $this->simple_results['baseline']['connect'][0]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['baseline']['connect'][0]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['baseline']['connect'][0]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['baseline']['connect'][0]['i1_3+i2_3+m1_3+m2_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['connect'][1]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['scim']['connect'][1]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['scim']['connect'][1]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['scim']['connect'][1]['i1_3+i2_3+m1_3+m2_3']['counts']; ?></td>
        <td>(<?php echo $this->simple_results['scim']['connect'][0]['i1_3+i2_3+m1_3+m2_3']['min']; ?>, <?php echo $this->simple_results['scim']['connect'][0]['i1_3+i2_3+m1_3+m2_3']['mean']; ?>, <?php echo $this->simple_results['scim']['connect'][0]['i1_3+i2_3+m1_3+m2_3']['max']; ?>) - <?php echo $this->simple_results['scim']['connect'][0]['i1_3+i2_3+m1_3+m2_3']['counts']; ?></td>
    </tr>
    </table>
    <h2>Detailed Results</h2>
    <h5 style="text-align: right;">*(min, mean, max) - counts</h5>

    <table class="table">
        <tr><td></td><td></td><td colspan="2">baseline</td><td colspan="2">scim</td></tr>
        <tr><td></td><td></td><td>Pretest</td><td>Posttest</td><td>Pretest</td><td>Posttest</td></tr>
        <tr><td rowspan="12" style="vertical-align: middle;">Summary</td>
            <td>S1</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['s1']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['s1']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['s1']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['s1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['s1']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['s1']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['s1']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['s1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['s1']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['s1']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['s1']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['s1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['s1']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['s1']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['s1']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['s1']['counts']; ?></td></tr>
        <tr>
            <td>S2</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['s2']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['s2']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['s2']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['s2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['s2']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['s2']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['s2']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['s2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['s2']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['s2']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['s2']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['s2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['s2']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['s2']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['s2']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['s2']['counts']; ?></td></tr>
        <tr>
            <td>S3</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['s3']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['s3']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['s3']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['s3']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['s3']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['s3']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['s3']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['s3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['s3']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['s3']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['s3']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['s3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['s3']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['s3']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['s3']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['s3']['counts']; ?></td></tr>
        <tr>
            <td>S4</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['s4']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['s4']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['s4']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['s4']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['s4']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['s4']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['s4']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['s4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['s4']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['s4']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['s4']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['s4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['s4']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['s4']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['s4']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['s4']['counts']; ?></td></tr>
        <tr>
            <td>C1</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['c1']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['c1']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['c1']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['c1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['c1']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['c1']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['c1']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['c1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['c1']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['c1']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['c1']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['c1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['c1']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['c1']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['c1']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['c1']['counts']; ?></td></tr>
        <tr>
            <td>C2</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['c2']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['c2']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['c2']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['c2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['c2']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['c2']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['c2']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['c2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['c2']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['c2']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['c2']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['c2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['c2']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['c2']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['c2']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['c2']['counts']; ?></td></tr>
        <tr>
            <td>C3</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['c3']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['c3']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['c3']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['c3']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['c3']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['c3']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['c3']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['c3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['c3']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['c3']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['c3']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['c3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['c3']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['c3']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['c3']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['c3']['counts']; ?></td></tr>
        <tr>
            <td>C4</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['c4']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['c4']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['c4']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['c4']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['c4']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['c4']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['c4']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['c4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['c4']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['c4']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['c4']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['c4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['c4']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['c4']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['c4']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['c4']['counts']; ?></td></tr>
        <tr>
            <td>I1</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['i1']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['i1']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['i1']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['i1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['i1']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['i1']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['i1']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['i1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['i1']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['i1']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['i1']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['i1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['i1']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['i1']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['i1']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['i1']['counts']; ?></td></tr>
        <tr>
            <td>I2</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['i2']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['i2']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['i2']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['i2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['i2']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['i2']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['i2']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['i2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['i2']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['i2']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['i2']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['i2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['i2']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['i2']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['i2']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['i2']['counts']; ?></td></tr>
        <tr>
            <td>M1</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['m1']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['m1']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['m1']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['m1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['m1']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['m1']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['m1']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['m1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['m1']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['m1']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['m1']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['m1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['m1']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['m1']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['m1']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['m1']['counts']; ?></td></tr>
        <tr>
            <td>M2</td>
            <td>(<?php echo $this->results['baseline']['summarytone'][1]['m2']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['m2']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][1]['m2']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][1]['m2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['summarytone'][0]['m2']['min']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['m2']['mean']; ?>, <?php echo $this->results['baseline']['summarytone'][0]['m2']['max']; ?>) - <?php echo $this->results['baseline']['summarytone'][0]['m2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][1]['m2']['min']; ?>, <?php echo $this->results['scim']['summarytone'][1]['m2']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][1]['m2']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][1]['m2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['summarytone'][0]['m2']['min']; ?>, <?php echo $this->results['scim']['summarytone'][0]['m2']['mean']; ?>, <?php echo $this->results['scim']['summarytone'][0]['m2']['max']; ?>) - <?php echo $this->results['scim']['summarytone'][0]['m2']['counts']; ?></td></tr>
        <tr><td rowspan="12" style="vertical-align: middle;">Tag</td>
            <td>S1</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['s1']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['s1']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['s1']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['s1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['s1']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['s1']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['s1']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['s1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['s1']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['s1']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['s1']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['s1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['s1']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['s1']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['s1']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['s1']['counts']; ?></td></tr>
        <tr>
            <td>S2</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['s2']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['s2']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['s2']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['s2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['s2']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['s2']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['s2']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['s2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['s2']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['s2']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['s2']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['s2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['s2']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['s2']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['s2']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['s2']['counts']; ?></td></tr>
        <tr>
            <td>S3</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['s3']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['s3']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['s3']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['s3']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['s3']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['s3']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['s3']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['s3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['s3']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['s3']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['s3']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['s3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['s3']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['s3']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['s3']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['s3']['counts']; ?></td></tr>
        <tr>
            <td>S4</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['s4']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['s4']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['s4']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['s4']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['s4']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['s4']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['s4']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['s4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['s4']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['s4']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['s4']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['s4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['s4']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['s4']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['s4']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['s4']['counts']; ?></td></tr>
        <tr>
            <td>C1</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['c1']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['c1']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['c1']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['c1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['c1']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['c1']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['c1']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['c1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['c1']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['c1']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['c1']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['c1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['c1']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['c1']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['c1']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['c1']['counts']; ?></td></tr>
        <tr>
            <td>C2</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['c2']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['c2']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['c2']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['c2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['c2']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['c2']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['c2']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['c2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['c2']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['c2']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['c2']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['c2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['c2']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['c2']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['c2']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['c2']['counts']; ?></td></tr>
        <tr>
            <td>C3</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['c3']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['c3']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['c3']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['c3']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['c3']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['c3']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['c3']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['c3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['c3']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['c3']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['c3']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['c3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['c3']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['c3']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['c3']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['c3']['counts']; ?></td></tr>
        <tr>
            <td>C4</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['c4']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['c4']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['c4']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['c4']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['c4']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['c4']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['c4']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['c4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['c4']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['c4']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['c4']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['c4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['c4']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['c4']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['c4']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['c4']['counts']; ?></td></tr>
        <tr>
            <td>I1</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['i1']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['i1']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['i1']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['i1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['i1']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['i1']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['i1']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['i1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['i1']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['i1']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['i1']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['i1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['i1']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['i1']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['i1']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['i1']['counts']; ?></td></tr>
        <tr>
            <td>I2</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['i2']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['i2']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['i2']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['i2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['i2']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['i2']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['i2']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['i2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['i2']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['i2']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['i2']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['i2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['i2']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['i2']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['i2']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['i2']['counts']; ?></td></tr>
        <tr>
            <td>M1</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['m1']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['m1']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['m1']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['m1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['m1']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['m1']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['m1']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['m1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['m1']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['m1']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['m1']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['m1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['m1']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['m1']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['m1']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['m1']['counts']; ?></td></tr>
        <tr>
            <td>M2</td>
            <td>(<?php echo $this->results['baseline']['tag'][1]['m2']['min']; ?>, <?php echo $this->results['baseline']['tag'][1]['m2']['mean']; ?>, <?php echo $this->results['baseline']['tag'][1]['m2']['max']; ?>) - <?php echo $this->results['baseline']['tag'][1]['m2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['tag'][0]['m2']['min']; ?>, <?php echo $this->results['baseline']['tag'][0]['m2']['mean']; ?>, <?php echo $this->results['baseline']['tag'][0]['m2']['max']; ?>) - <?php echo $this->results['baseline']['tag'][0]['m2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][1]['m2']['min']; ?>, <?php echo $this->results['scim']['tag'][1]['m2']['mean']; ?>, <?php echo $this->results['scim']['tag'][1]['m2']['max']; ?>) - <?php echo $this->results['scim']['tag'][1]['m2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['tag'][0]['m2']['min']; ?>, <?php echo $this->results['scim']['tag'][0]['m2']['mean']; ?>, <?php echo $this->results['scim']['tag'][0]['m2']['max']; ?>) - <?php echo $this->results['scim']['tag'][0]['m2']['counts']; ?></td></tr>
        <tr><td rowspan="12" style="vertical-align: middle;">Connect</td>
            <td>S1</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['s1']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['s1']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['s1']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['s1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['s1']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['s1']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['s1']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['s1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['s1']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['s1']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['s1']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['s1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['s1']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['s1']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['s1']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['s1']['counts']; ?></td></tr>
        <tr>
            <td>S2</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['s2']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['s2']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['s2']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['s2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['s2']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['s2']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['s2']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['s2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['s2']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['s2']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['s2']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['s2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['s2']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['s2']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['s2']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['s2']['counts']; ?></td></tr>
        <tr>
            <td>S3</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['s3']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['s3']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['s3']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['s3']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['s3']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['s3']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['s3']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['s3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['s3']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['s3']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['s3']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['s3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['s3']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['s3']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['s3']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['s3']['counts']; ?></td></tr>
        <tr>
            <td>S4</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['s4']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['s4']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['s4']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['s4']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['s4']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['s4']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['s4']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['s4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['s4']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['s4']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['s4']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['s4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['s4']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['s4']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['s4']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['s4']['counts']; ?></td></tr>
        <tr>
            <td>C1</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['c1']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['c1']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['c1']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['c1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['c1']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['c1']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['c1']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['c1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['c1']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['c1']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['c1']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['c1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['c1']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['c1']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['c1']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['c1']['counts']; ?></td></tr>
        <tr>
            <td>C2</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['c2']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['c2']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['c2']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['c2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['c2']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['c2']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['c2']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['c2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['c2']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['c2']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['c2']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['c2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['c2']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['c2']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['c2']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['c2']['counts']; ?></td></tr>
        <tr>
            <td>C3</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['c3']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['c3']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['c3']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['c3']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['c3']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['c3']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['c3']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['c3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['c3']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['c3']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['c3']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['c3']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['c3']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['c3']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['c3']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['c3']['counts']; ?></td></tr>
        <tr>
            <td>C4</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['c4']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['c4']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['c4']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['c4']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['c4']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['c4']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['c4']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['c4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['c4']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['c4']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['c4']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['c4']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['c4']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['c4']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['c4']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['c4']['counts']; ?></td></tr>
        <tr>
            <td>I1</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['i1']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['i1']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['i1']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['i1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['i1']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['i1']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['i1']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['i1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['i1']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['i1']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['i1']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['i1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['i1']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['i1']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['i1']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['i1']['counts']; ?></td></tr>
        <tr>
            <td>I2</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['i2']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['i2']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['i2']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['i2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['i2']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['i2']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['i2']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['i2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['i2']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['i2']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['i2']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['i2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['i2']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['i2']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['i2']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['i2']['counts']; ?></td></tr>
        <tr>
            <td>M1</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['m1']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['m1']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['m1']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['m1']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['m1']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['m1']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['m1']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['m1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['m1']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['m1']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['m1']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['m1']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['m1']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['m1']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['m1']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['m1']['counts']; ?></td></tr>
        <tr>
            <td>M2</td>
            <td>(<?php echo $this->results['baseline']['connect'][1]['m2']['min']; ?>, <?php echo $this->results['baseline']['connect'][1]['m2']['mean']; ?>, <?php echo $this->results['baseline']['connect'][1]['m2']['max']; ?>) - <?php echo $this->results['baseline']['connect'][1]['m2']['counts']; ?></td>
            <td>(<?php echo $this->results['baseline']['connect'][0]['m2']['min']; ?>, <?php echo $this->results['baseline']['connect'][0]['m2']['mean']; ?>, <?php echo $this->results['baseline']['connect'][0]['m2']['max']; ?>) - <?php echo $this->results['baseline']['connect'][0]['m2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][1]['m2']['min']; ?>, <?php echo $this->results['scim']['connect'][1]['m2']['mean']; ?>, <?php echo $this->results['scim']['connect'][1]['m2']['max']; ?>) - <?php echo $this->results['scim']['connect'][1]['m2']['counts']; ?></td>
            <td>(<?php echo $this->results['scim']['connect'][0]['m2']['min']; ?>, <?php echo $this->results['scim']['connect'][0]['m2']['mean']; ?>, <?php echo $this->results['scim']['connect'][0]['m2']['max']; ?>) - <?php echo $this->results['scim']['connect'][0]['m2']['counts']; ?></td></tr>
    </table>
</div>
<br>
<br>

<script>
$(function() {
    window.onbeforeunload = "";
});
</script>
<!-- separate display: version 1
    <tr><td>Summary</td><td>(<?php echo $this->baseline_summarytone_pre_min; ?>, <?php echo $this->baseline_summarytone_pre_mean; ?>, <?php echo $this->baseline_summarytone_pre_max; ?>) - <?php echo $this->baseline_summarytone_pre_counts; ?></td><td>(<?php echo $this->baseline_summarytone_post_min; ?>, <?php echo $this->baseline_summarytone_post_mean; ?>, <?php echo $this->baseline_summarytone_post_max; ?>) - <?php echo $this->baseline_summarytone_post_counts; ?></td><td>(<?php echo $this->scim_summarytone_pre_min; ?>, <?php echo $this->scim_summarytone_pre_mean; ?>, <?php echo $this->scim_summarytone_pre_max; ?>) - <?php echo $this->scim_summarytone_pre_counts; ?></td><td>(<?php echo $this->scim_summarytone_post_mean; ?>, <?php echo $this->scim_summarytone_post_min; ?>, <?php echo $this->scim_summarytone_post_max; ?>) - <?php echo $this->scim_summarytone_post_counts; ?></td></tr>
    <tr><td>Tag</td><td>(<?php echo $this->baseline_tag_pre_min; ?>, <?php echo $this->baseline_tag_pre_mean; ?>, <?php echo $this->baseline_tag_pre_max; ?>) - <?php echo $this->baseline_tag_pre_counts; ?></td><td>(<?php echo $this->baseline_tag_post_min; ?>, <?php echo $this->baseline_tag_post_mean; ?>, <?php echo $this->baseline_tag_post_max; ?>) - <?php echo $this->baseline_tag_post_counts; ?></td><td>(<?php echo $this->scim_tag_pre_min; ?>, <?php echo $this->scim_tag_pre_mean; ?>, <?php echo $this->scim_tag_pre_max; ?>) - <?php echo $this->scim_tag_pre_counts; ?></td><td>(<?php echo $this->scim_tag_post_mean; ?>, <?php echo $this->scim_tag_post_min; ?>, <?php echo $this->scim_tag_post_max; ?>) - <?php echo $this->scim_tag_post_counts; ?></td></tr>
    <tr><td>Connect</td><td>(<?php echo $this->baseline_connect_pre_min; ?>, <?php echo $this->baseline_connect_pre_mean; ?>, <?php echo $this->baseline_connect_pre_max; ?>) - <?php echo $this->baseline_connect_pre_counts; ?></td><td>(<?php echo $this->baseline_connect_post_min; ?>, <?php echo $this->baseline_connect_post_mean; ?>, <?php echo $this->baseline_connect_post_max; ?>) - <?php echo $this->baseline_connect_post_counts; ?></td><td>(<?php echo $this->scim_connect_pre_min; ?>, <?php echo $this->scim_connect_pre_mean; ?>, <?php echo $this->scim_connect_pre_max; ?>) - <?php echo $this->scim_connect_pre_counts; ?></td><td>(<?php echo $this->scim_connect_post_mean; ?>, <?php echo $this->scim_connect_post_min; ?>, <?php echo $this->scim_connect_post_max; ?>) - <?php echo $this->scim_connect_post_counts; ?></td></tr>
    <tr><td><br>Summary</td><td>mean: <?php echo $this->baseline_summarytone_pre_mean; ?><br>min: <?php echo $this->baseline_summarytone_pre_min; ?><br>max: <?php echo $this->baseline_summarytone_pre_max; ?><br></td><td>mean: <?php echo $this->baseline_summarytone_post_mean; ?><br>min: <?php echo $this->baseline_summarytone_post_min; ?><br>max: <?php echo $this->baseline_summarytone_post_max; ?><br></td><td>mean: <?php echo $this->scim_summarytone_pre_mean; ?><br>min: <?php echo $this->scim_summarytone_pre_min; ?><br>max: <?php echo $this->scim_summarytone_pre_max; ?><br></td><td>mean: <?php echo $this->scim_summarytone_post_mean; ?><br>min: <?php echo $this->scim_summarytone_post_min; ?><br>max: <?php echo $this->scim_summarytone_post_max; ?><br></td></tr>
    <tr><td><br>Tag</td><td>mean: <?php echo $this->baseline_tag_pre_mean; ?><br>min: <?php echo $this->baseline_tag_pre_min; ?><br>max: <?php echo $this->baseline_tag_pre_max; ?><br></td><td>mean: <?php echo $this->baseline_tag_post_mean; ?><br>min: <?php echo $this->baseline_tag_post_min; ?><br>max: <?php echo $this->baseline_tag_post_max; ?><br></td><td>mean: <?php echo $this->scim_tag_pre_mean; ?><br>min: <?php echo $this->scim_tag_pre_min; ?><br>max: <?php echo $this->scim_tag_pre_max; ?><br></td><td>mean: <?php echo $this->scim_tag_post_mean; ?><br>min: <?php echo $this->scim_tag_post_min; ?><br>max: <?php echo $this->scim_tag_post_max; ?><br></td></tr>
    <tr><td><br>Connect</td><td>mean: <?php echo $this->baseline_connect_pre_mean; ?><br>min: <?php echo $this->baseline_connect_pre_min; ?><br>max: <?php echo $this->baseline_connect_pre_max; ?><br></td><td>mean: <?php echo $this->baseline_connect_post_mean; ?><br>min: <?php echo $this->baseline_connect_post_min; ?><br>max: <?php echo $this->baseline_connect_post_max; ?><br></td><td>mean: <?php echo $this->scim_connect_pre_mean; ?><br>min: <?php echo $this->scim_connect_pre_min; ?><br>max: <?php echo $this->scim_connect_pre_max; ?><br></td><td>mean: <?php echo $this->scim_connect_post_mean; ?><br>min: <?php echo $this->scim_connect_post_min; ?><br>max: <?php echo $this->scim_connect_post_max; ?><br></td></tr>
-->
